# report_agent/nlg/report_service.py
from pathlib import Path
from typing import Sequence

from report_agent.metrics.metrics_loader import MetricsLoader
from report_agent.metrics.metrics_registry import MetricsRegistry
from report_agent.nlg.html_report import render_html_report


def generate_html_report(
    model: str,
    connector,                   
    out_dir: str = "reports",
    plots_subdir: str = "plots",
    data_subdir: str = "data",
    text_subdir: str = "text",
) -> str:
    """
    Run the interpreter, download plots, save CSV and narrative text, and write an HTML report.

    Returns the HTML file path as a string.

    Side effects (under `out_dir`):
      - plots/<model>_*.png        – plots generated by the CI container
      - data/<model>.csv           – raw time series (re-fetched from ClickHouse)
      - text/<model>.txt           – plain-text narrative from the LLM
      - <date>_<model>.html        – rendered HTML report
    """
    out_root = Path(out_dir)
    out_root.mkdir(parents=True, exist_ok=True)

    # 1) Run interpreter to get narrative text
    narrative = connector.run_report(model)

    # 1b) Save narrative text for later (used by portfolio summary LLM)
    text_dir = out_root / text_subdir
    text_dir.mkdir(parents=True, exist_ok=True)
    text_path = text_dir / f"{model}.txt"
    text_path.write_text(narrative, encoding="utf-8")

    # 2) Download any plots the model created
    plots_dir_path = out_root / plots_subdir
    plots_dir_path.mkdir(parents=True, exist_ok=True)
    saved = connector.download_artifacts(output_dir=str(plots_dir_path))
    image_paths: Sequence[str] = [
        p
        for p in saved
        if not str(p).startswith("ERROR:")
        and str(p).lower().endswith((".png", ".jpg", ".jpeg", ".gif"))
    ]

    # 3) Save raw CSV for convenience (re-fetching avoids coupling to temp paths)
    reg = MetricsRegistry()
    hist = reg.get_history_days(model)
    df = MetricsLoader().fetch_time_series(model, lookback_days=hist)

    data_dir = out_root / data_subdir
    data_dir.mkdir(parents=True, exist_ok=True)
    data_path = data_dir / f"{model}.csv"
    df.to_csv(data_path, index=False)

    # 4) Render HTML
    html_path = render_html_report(
        model=model,
        narrative_markdown=narrative,
        image_paths=[str(Path(p)) for p in image_paths],
        data_csv_path=str(data_path),
        out_dir=str(out_root),
    )
    return html_path