metrics:
  - model: execution_txs_info_daily
    thresholds:
      pct_change: 5        
      anomaly_count: 1     

  - model: consensus_validators_balances_dist_daily
    thresholds:
      pct_change: 3      

  - model: p2p_peers_clients_daily
    thresholds:
      pct_change: 10     
      anomaly_count: 2

  - model: yields_sdai_rate_daily
    thresholds:
      pct_change: 1        

  - model: api_p2p_discv4_clients_daily
    history_days: 180   # enough baseline; raw rows only